[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
 autocmd FileType python setlocal completeopt-=preview
 let g:jedi#popup_on_dot = 0
'''
on_i = 1

[[plugins]]
repo = 'ervandew/supertab'
hook_add = '''
let g:SuperTabDefaultCompletionType = "<c-n>"
'''
on_ft = 'python'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = 'python'

[[plugins]]
repo = "nathanaelkane/vim-indent-guides"
